### ISSUE TITLE
Feature Request: Disambiguate using UMIs 

### ISSUE THREAD

**Issue by harish0201** [clintval/cvbio#90]
Hi! 

I'm trying to think if this is something that might be useful. Currently, I'm running disambiguate on two sets of bams, output by CellRanger. I was wondering, what happens when there are ambiguous reads that map to different genomes/references, should we just discard the ambiguous reads, or the shared UMIs as well.

**Comment by clintval** [comment]
I'm glad you found this (relatively hidden) tool and are finding it useful!

That is a curious idea and I think it makes sense to develop such a strategy.

Could you reveal more about your experimental design and where the cells are coming from?

The way I wrote the tool, we can order template alignments by any data/metadata. Here is the default ordering:

https://github.com/clintval/cvbio/blob/ed8b7612bf4ed20fe6d08d4a8ae82ebbb5d6215c/tools/src/io/cvbio/tools/disambiguate/TemplateOrdering.scala#L18-L40

The tool then takes that ordering for a set of alignments for a template and picks the best match:

https://github.com/clintval/cvbio/blob/ed8b7612bf4ed20fe6d08d4a8ae82ebbb5d6215c/tools/src/io/cvbio/tools/disambiguate/DisambiguationStrategy.scala#L29-L31

However, the tool does not consider inter-template information when deciding to disambiguate like we would need to do for cell barcodes. I'm curious, does your BAM file have just the `RX` tag filled in for UMI or are there are other assay specific tags you would want to leverage?

**Comment by clintval** [comment]
Now that I work at @fulcrumgenomics I have limited time to contribute to open source so I may not have the bandwidth to take this on. However, if you'd like to contract with us, it's relatively easy to commission us to complete work like this: https://fulcrumgenomics.com/

**Comment by clintval** [comment]
I'm also open and eager to learn if you have suggestions for making this tool more visible (it is currently buried in a personal toolkit, and maybe should be standalone?) and if the user experience or documentation needs improvement!

**Comment by harish0201** [comment]
No worries! 

I just wanted to check if I could disambiguate the reads mapping to exogenous sequences from the reference genome. Disambiguate works fine for that, but I was wondering if I should use UMI information to better resolve the alignments.

Cellranger tends to store the corrected UMI in the "UB" bam tag, and "UR" for the uncorrected ones. I think we should use that instead of the RX tag (which seems to be absent in the bam?!)

I just also realized that I've been using Disambiguate for a long time now! But as such, since it's nicely bundled with a bunch of useful tools, it should be fine as it is.

**Comment by harish0201** [comment]
I also just closed this issue, since it's mostly discussion at this point :)
